import { loadTaxRates, loadRebuyMonths, loadManualPortfolioValues, loadMarketStatus } from "./settings.js";

export const API_BASE = "";

export const AUTH_TOKEN_KEY = "northstar-secure-token";

export const SPLIT_SCAN_KEY = "northstar-last-split-scan";

export const TAX_SETTINGS_KEY = "northstar-tax-settings";

export const REBUY_MONTHS_KEY = "northstar-rebuy-months";

export const DEFAULT_REBUY_MONTHS = 6;

export const MANUAL_PORTFOLIO_KEY = "northstar-manual-portfolio-values";

export const MARKET_STATUS_KEY = "northstar-market-status";

export const DEFAULT_FEE = 1.5;

export const DEFAULT_TAX_RATES = { tr: 0, usa: 20, crypto: 0 };

export const BUILD_VERSION = "20260515w";

export const TODAY_ISO = new Date().toISOString().slice(0, 10);

export const TR_YAHOO_SYMBOL_OVERRIDES = {
  ALTINS1: "ALTINS1",
  // BTC bought in TL lives in the TR tab; the worker derives BTC-TRY from
  // BTC-USD × TCMB USD/TRY (no BIST/Yahoo listing exists for it).
  BTC: "BTC-TRY",
  DMLKTG: "DMLKT",
  "DMLKT.G": "DMLKT",
  "GLDR.F": "GLDTR.IS",
  "GLDTR.F": "GLDTR.IS",
  "GMSTR.F": "GMSTR.IS",
  RTLAB: "RTALB.IS",
  RTALB: "RTALB.IS",
  "USDTR.F": "USDTR.IS",
};


export const seedTransactions = [
  { symbol: "TLT", date: "2023-11-02", pcs: 58, price: 86.5, amount: 5017, fee: 1.5, total: 5018.5, note: "" },
  { symbol: "TSLA", date: "2023-11-22", pcs: 43, price: 232, amount: 9976, fee: 1.5, total: 9977.5, note: "" },
  { symbol: "NVDA", date: "2023-11-24", pcs: 20, price: 483, amount: 9660, fee: 1.5, total: 9661.5, note: "a" },
  { symbol: "GLD", date: "2023-12-08", pcs: 26, price: 186, amount: 4836, fee: 1.5, total: 4837.5, note: "" },
  { symbol: "NVDA", date: "2024-02-16", pcs: -13, price: 744, amount: -9672, fee: 1.5, total: -9670.5, note: "a" },
  { symbol: "TSLA", date: "2024-06-05", pcs: 57, price: 174, amount: 9918, fee: 1.5, total: 9919.5, note: "" },
  { symbol: "QQQ", date: "2024-08-16", pcs: 10, price: 473, amount: 4730, fee: 1.5, total: 4731.5, note: "" },
  { symbol: "MSTR", date: "2024-09-05", pcs: 41, price: 121.9, amount: 4997.9, fee: 1.5, total: 4999.4, note: "" },
  { symbol: "SOFI", date: "2024-10-02", pcs: 657, price: 7.6, amount: 4993.2, fee: 1.5, total: 4994.7, note: "" },
  { symbol: "AMZN", date: "2024-10-23", pcs: 26, price: 188, amount: 4888, fee: 1.5, total: 4889.5, note: "" },
  { symbol: "AMD", date: "2024-12-09", pcs: 37, price: 132, amount: 4884, fee: 1.5, total: 4885.5, note: "" },
  { symbol: "SEZL", date: "2025-01-17", pcs: 126, price: 38.333333333333336, amount: 4830, fee: 1.5, total: 4831.5, note: "b" },
  { symbol: "CRDO", date: "2025-01-27", pcs: 19, price: 53, amount: 1007, fee: 1.5, total: 1008.5, note: "" },
  { symbol: "SEZL", date: "2025-05-22", pcs: -56, price: 103, amount: -5768, fee: 1.5, total: -5766.5, note: "b" },
  { symbol: "NBIS", date: "2025-05-22", pcs: 133, price: 37.5, amount: 4987.5, fee: 1.5, total: 4989, note: "" },
  { symbol: "HIMS", date: "2025-06-23", pcs: 114, price: 43.5, amount: 4959, fee: 1.5, total: 4960.5, note: "" },
  { symbol: "OSCR", date: "2025-07-11", pcs: 353, price: 14.138810198300283, amount: 4991, fee: 3, total: 4994, note: "", chainId: "OSCR::merged-2025-07" },
  { symbol: "APP", date: "2025-08-14", pcs: 11, price: 429, amount: 4719, fee: 1.5, total: 4720.5, note: "" },
  { symbol: "RKLB", date: "2025-08-18", pcs: 100, price: 45.48, amount: 4548, fee: 1.5, total: 4549.5, note: "" },
  { symbol: "SMCI", date: "2025-09-12", pcs: 111, price: 45.03, amount: 4998.33, fee: 1.5, total: 4999.83, note: "d" },
  { symbol: "RBRK", date: "2025-09-15", pcs: 66, price: 75.67, amount: 4994.22, fee: 1.5, total: 4995.72, note: "" },
  { symbol: "SLNH", date: "2025-09-25", pcs: 356, price: 2.8, amount: 996.8, fee: 1.5, total: 998.3, note: "" },
  { symbol: "RDDT", date: "2025-10-02", pcs: 25, price: 199, amount: 4975, fee: 1.5, total: 4976.5, note: "" },
  { symbol: "INFQ", date: "2025-10-06", pcs: 66, price: 14.98, amount: 988.68, fee: 1.5, total: 990.18, note: "" },
  { symbol: "IMSR", date: "2025-10-06", pcs: 53, price: 18.69, amount: 990.57, fee: 1.5, total: 992.07, note: "e" },
  { symbol: "CRWV", date: "2025-10-09", pcs: 26, price: 139, amount: 3614, fee: 1.5, total: 3615.5, note: "c" },
  { symbol: "IOT", date: "2025-10-09", pcs: 24, price: 40, amount: 960, fee: 1.5, total: 961.5, note: "" },
  { symbol: "MSTR", date: "2025-10-31", pcs: 79, price: 272.59, amount: 21534.61, fee: 1.5, total: 21536.11, note: "" },
  { symbol: "AXON", date: "2025-11-07", pcs: 47, price: 606.2, amount: 28491.4, fee: 1.5, total: 28492.9, note: "" },
  { symbol: "CRWV", date: "2025-12-22", pcs: -26, price: 84.1, amount: -2186.6, fee: 1.5, total: -2185.1, note: "c" },
  { symbol: "CRWV", date: "2025-12-23", pcs: 26, price: 83.4, amount: 2168.4, fee: 1.5, total: 2169.9, note: "c" },
  { symbol: "SMCI", date: "2025-12-29", pcs: -111, price: 30.31, amount: -3364.41, fee: 1.5, total: -3362.91, note: "d" },
  { symbol: "SMCI", date: "2025-12-29", pcs: 112, price: 30.02, amount: 3362.24, fee: 1.5, total: 3363.74, note: "d" },
  { symbol: "IMSR", date: "2025-12-30", pcs: -53, price: 6.02, amount: -319.06, fee: 1.5, total: -317.56, note: "e" },
  { symbol: "HOOD", date: "2026-02-04", pcs: 12, price: 83.21, amount: 998.52, fee: 1.5, total: 1000.02, note: "" },
  { symbol: "EOSE", date: "2026-02-13", pcs: 70, price: 10.8, amount: 756, fee: 1.5, total: 757.5, note: "" },
  { symbol: "IMSR", date: "2026-03-30", pcs: 53, price: 5.95, amount: 315.35, fee: 1.5, total: 316.85, note: "e" },
  { symbol: "IREN", date: "2026-03-31", pcs: 156, price: 32, amount: 4992, fee: 1.5, total: 4993.5, note: "" },
];


export const elements = {
  authShell: document.getElementById("auth-shell"),
  appShell: document.getElementById("app-shell"),
  currentUser: document.getElementById("current-user"),
  loginTab: document.getElementById("login-tab"),
  registerTab: document.getElementById("register-tab"),
  loginForm: document.getElementById("login-form"),
  registerForm: document.getElementById("register-form"),
  loginSubmit: document.querySelector("#login-form button[type='submit']"),
  registerSubmit: document.querySelector("#register-form button[type='submit']"),
  authFeedback: document.getElementById("auth-feedback"),
  loginUsername: document.getElementById("login-username"),
  loginPassword: document.getElementById("login-password"),
  registerUsername: document.getElementById("register-username"),
  registerPassword: document.getElementById("register-password"),
  logoutButton: document.getElementById("logout-button"),
  adminButton: document.getElementById("admin-button"),
  adminModal: document.getElementById("admin-modal"),
  adminModalBackdrop: document.getElementById("admin-modal-backdrop"),
  adminModalClose: document.getElementById("admin-modal-close"),
  adminModalFeedback: document.getElementById("admin-modal-feedback"),
  adminUsersBody: document.getElementById("admin-users-body"),
  trViewTab: document.getElementById("tr-view-tab"),
  abdViewTab: document.getElementById("abd-view-tab"),
  cryptoViewTab: document.getElementById("crypto-view-tab"),
  cashflowViewTab: document.getElementById("cashflow-view-tab"),
  quarterPlusViewTab: document.getElementById("quarter-plus-view-tab"),
  quarterChartViewTab: document.getElementById("quarter-chart-view-tab"),
  splitsViewTab: document.getElementById("splits-view-tab"),
  statusViewTab: document.getElementById("status-view-tab"),
  trShell: document.getElementById("tr-shell"),
  trEntryForm: document.getElementById("tr-entry-form"),
  trSymbolInput: document.getElementById("tr-symbol-input"),
  trBuyDateInput: document.getElementById("tr-buy-date-input"),
  trQuantityInput: document.getElementById("tr-quantity-input"),
  trBuyTotalInput: document.getElementById("tr-buy-total-input"),
  trTable: document.getElementById("tr-table"),
  abdShell: document.getElementById("abd-shell"),
  cryptoShell: document.getElementById("crypto-shell"),
  cryptoEntryForm: document.getElementById("crypto-entry-form"),
  cryptoSymbolInput: document.getElementById("crypto-symbol-input"),
  cryptoDateInput: document.getElementById("crypto-date-input"),
  cryptoQuantityInput: document.getElementById("crypto-quantity-input"),
  cryptoTotalInput: document.getElementById("crypto-total-input"),
  cryptoTable: document.getElementById("crypto-table"),
  cashflowShell: document.getElementById("cashflow-shell"),
  quarterPlusShell: document.getElementById("quarter-plus-shell"),
  quarterChartShell: document.getElementById("quarter-chart-shell"),
  splitsShell: document.getElementById("splits-shell"),
  statusShell: document.getElementById("status-shell"),
  positionsTable: document.getElementById("positions-table"),
  portfolioProfit: document.getElementById("portfolio-profit"),
  portfolioProfitPercent: document.getElementById("portfolio-profit-percent"),
  portfolioChartWrap: document.getElementById("portfolio-chart-wrap"),
  trPortfolioProfit: document.getElementById("tr-portfolio-profit"),
  trPortfolioProfitPercent: document.getElementById("tr-portfolio-profit-percent"),
  trPortfolioChartWrap: document.getElementById("tr-portfolio-chart-wrap"),
  cryptoPortfolioProfit: document.getElementById("crypto-portfolio-profit"),
  cryptoPortfolioProfitPercent: document.getElementById("crypto-portfolio-profit-percent"),
  cryptoPortfolioChartWrap: document.getElementById("crypto-portfolio-chart-wrap"),
  portfolioClosedProfit: document.getElementById("portfolio-closed-profit"),
  portfolioClosedProfitPercent: document.getElementById("portfolio-closed-profit-percent"),
  trPortfolioClosedProfit: document.getElementById("tr-portfolio-closed-profit"),
  trPortfolioClosedProfitPercent: document.getElementById("tr-portfolio-closed-profit-percent"),
  cryptoPortfolioClosedProfit: document.getElementById("crypto-portfolio-closed-profit"),
  cryptoPortfolioClosedProfitPercent: document.getElementById("crypto-portfolio-closed-profit-percent"),
  transactionForm: document.getElementById("transaction-form"),
  symbolInput: document.getElementById("symbol-input"),
  sideInput: document.getElementById("side-input"),
  dateInput: document.getElementById("date-input"),
  sharesInput: document.getElementById("shares-input"),
  totalInput: document.getElementById("total-input"),
  noteInput: document.getElementById("note-input"),
  cashflowNote: document.getElementById("cashflow-note"),
  cashflowDate: document.getElementById("cashflow-date"),
  cashflowTry: document.getElementById("cashflow-try"),
  cashflowUsd: document.getElementById("cashflow-usd"),
  cashflowUsdt: document.getElementById("cashflow-usdt"),
  cashflowAdd: document.getElementById("cashflow-add"),
  taxRateTr: document.getElementById("tax-rate-tr"),
  taxRateUsa: document.getElementById("tax-rate-usa"),
  taxRateCrypto: document.getElementById("tax-rate-crypto"),
  rebuyMonths: document.getElementById("rebuy-months"),
  cashflowAbdPortfolioUsd: document.getElementById("cashflow-abd-portfolio-usd"),
  cashflowTrPortfolioValue: document.getElementById("cashflow-tr-portfolio-value"),
  refreshDataButton: document.getElementById("refresh-data-button"),
  manualAbdPortfolioUsd: document.getElementById("manual-abd-portfolio-usd"),
  manualTrPortfolioTry: document.getElementById("manual-tr-portfolio-try"),
  latestRateLabel: document.getElementById("latest-rate-label"),
  statusSummary: document.getElementById("status-summary"),
  statusChartSummary: document.getElementById("status-chart-summary"),
  statusPerformanceChart: document.getElementById("status-performance-chart"),
  years2Summary: document.getElementById("years2-summary"),
  years2Body: document.getElementById("years2-body"),
  yearsQuarterSummary: document.getElementById("years-quarter-summary"),
  yearsQuarterBody: document.getElementById("years-quarter-body"),
  quarterPlusSummary: document.getElementById("quarter-plus-summary"),
  quarterPlusBody: document.getElementById("quarter-plus-body"),
  quarterDebug: document.getElementById("quarter-debug"),
  yearsQuarterChart: document.getElementById("years-quarter-chart"),
  yearsQuarterChart2: document.getElementById("years-quarter-chart-2"),
  yearsQuarterChart3: document.getElementById("years-quarter-chart-3"),
  chart2StartDate: document.getElementById("chart2-start-date"),
  chart2Hint: document.querySelector(".quarter-chart2-hint"),
  splitsSummary: document.getElementById("splits-summary"),
  splitsBody: document.getElementById("splits-body"),
  statusMessageList: document.getElementById("status-message-list"),
  cashflowSummaryBody: document.getElementById("cashflow-summary-body"),
  cashflowProfitValue: document.getElementById("cashflow-profit-value"),
  cashflowBody: document.getElementById("cashflow-body"),
};


export const state = {
  session: null,
  authToken: localStorage.getItem(AUTH_TOKEN_KEY) || "",
  activeView: "quarterChart",
  transactions: [],
  trRows: [],
  cryptoRows: [],
  cryptoOpenLots: [],
  trOpenLots: [],
  trClosedLots: [],
  cryptoClosedLots: [],
  cryptoEditingIndex: null,
  cryptoSaving: false,
  cryptoPricesBySymbol: new Map(),
  cryptoCandlesBySymbol: new Map(),
  trEditingId: null,
  trSaving: false,
  trAutoSaveToken: 0,
  trPricesBySymbol: new Map(),
  trCandlesBySymbol: new Map(),
  trSplitsBySymbol: new Map(),
  openLots: [],
  closedLots: [],
  pricesBySymbol: new Map(),
  candlesBySymbol: new Map(),
  splitsBySymbol: new Map(),
  gs3mByMonth: new Map(),
  gs3mStatus: { source: "", latestDate: "", pointCount: 0, refreshError: "" },
  autoSaveToken: 0,
  priceRefreshToken: 0,
  editingIndex: null,
  saving: false,
  cashFlowMovements: [],
  cashFlowEditingId: null,
  cashFlowSaving: false,
  cashFlowRates: {},
  cashFlowLatestRate: null,
  cashFlowLoadError: "",
  cashFlowMarketDataError: "",
  cashFlowStatusMessage: "",
  cashFlowYieldStatus: { usdMissingMonths: 0, tryMissingMonths: 0, message: "" },
  cashFlowYields: { usd: { points: [] }, try: { points: [] } },
  cashFlowMarketRefreshing: false,
  performance: { loading: false, loaded: false, messages: [], series: [], history: {}, rates: {} },
  returnCalc: { loading: false, loaded: false, messages: [], history: {}, rates: {} },
  quarterCalc: { loading: false, loaded: false, messages: [], history: {}, rates: {} },
  quarterRowsCache: null,
  quarterPlusRowsCache: null,
  quarterCacheUpdatedAt: "",
  auditMessages: [],
  auditRowsCache: null,
  auditDebugDate: "2023-04-13",
  marketDataMessages: [],
  marketDataMessageBuckets: {},
  calculatedCacheMessages: [],
  manualPortfolio: loadManualPortfolioValues(),
  taxRates: loadTaxRates(),
  rebuyMonths: loadRebuyMonths(),
  marketPreloadStarted: false,
  marketStatus: loadMarketStatus(),
};

